### PR TITLE
Added Czech translation.

### PR DESCRIPTION
**Pull request by paadza**
Just added the Czech translation. The file name is cs_CZ.po. Thanks for quickgui!

### CODE REVIEW

**Comment by philclifford** [comment]
Excellent - thanks @paadza ! As @ymauray had to teach me - could you also add it to the list of supported languages in  lib/src/app.dart please?

**Comment by paadza** [comment]
Sure thing. I did it. Thanks for letting me know, what file to edit :-). Anything else to add or edit? Thanks!

**Comment by philclifford** [comment]
You're welcome! Should be all you need. You might want to look at PR #42 It proposes an additional translation requirement if it gets merged, and you'll see I added the required existing translations via a PR to @WillyJimmyDev which he's kindly merged.  Not saying you need to do the same (actually you probably should not!), but it might be worth having an extra commit ready to push (or merge and push) in case @ymauray merges #42 first.  Hopefully that's not too confusing!!

**Comment by paadza** [comment]
Oh.. thanks again. I added the "Download cancelled" string translation to the Czech language. Thanks!

**Pull request merged**
