### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by philclifford**
First effort at Italian translation.

Sono estremamente grato per tutte le correzioni e i suggerimenti.
Je suis extrêmement reconnaissant pour toutes les corrections et suggestions.
Tha mi air leth taingeil airson gach ceartachadh agus moladh.
Für alle Korrekturen und Anregungen bin ich überaus dankbar.

Any and all corrections and suggestions gratefully received.

### CODE REVIEW

**Comment by ymauray** [comment]
Hello! Could you please add `it` as a supported language in lib/src/app.dart ? Thanks!

**Comment by philclifford** [comment]
Hi, I've touched my first dart :-)  Done.

**Comment by ymauray** [comment]
Looks good, thank you !

**Comment by philclifford** [comment]
Mon plaisir.

**Pull request merged**
