### PR TITLE
Mixin preferences: Refactored shared preferences functions to be generic setters/getters used as a mixin

### PR DESCRIPTION
**Pull request by ElanMan**
Refactored shared preferences functions to be generic setters/getters using key/values to allow for multiple preferences to be stored. Refactored the shared preferences functions as a mixin for ease of use. Directory change is now remembered across the app pages.

### CODE REVIEW

**Comment by ymauray** [comment]
Thanks. I'll have a look at this. 

There are a lot of changes that are cosmetics only - I suspect you use 80 columns, I use 160 because 80 is way too small.
I should make a note of this in the README.

I like the idea of having the settings as a mixin, so I'm interested in this PR.

If you have the time and are willing to do so, can you push a new version with the code formated with 160 columns ?

Also, I think you've left the pubscpec commit from your previous PR in this.

Again, thanks for your contribution !

**Comment by ymauray** [comment]
Awesome, thanks ! I'll have a look at that tonight !

**Comment by ElanMan** [comment]
Hi Yannick, my Dart formatter was set to 80 columns which I've now changed to 160. I've had a few issues with git. If there are any problems, please let me know :)

**Review by ymauray — APPROVED** [review]
It looks good. Thanks again for contributing, and sorry for the delay !

**Pull request merged**
